baseURL = "https://danub-io.github.io/gospelreads/"
title = "Gospel Reads"
theme = "blowfish"
defaultContentLanguage = "pt-br"

# Configuração que faltava para corrigir o erro
[languages]
  [languages.pt-br]
    languageName = "Português (Brasil)"
    title = "Gospel Reads"
    weight = 1

enableRobotsTXT = true
summaryLength = 30
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'