languageCode = "pt-br"
languageName = "Português (Brasil)"
weight = 6
title = "Gospel Reads"

[params]
  displayName = "Português (Brasil)"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "2 de January de 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Um tema poderoso e leve para Hugo."

[params.author]
  name = "Dan"
  image = "img/blowfish_logo.png"
  headline = "Gospel Reads"
  bio = "Reflexões e leituras."
