backend:
  name: github
  repo: danub-io/gospelreads
  branch: main # Branch principal

media_folder: "static/images" # Onde as imagens dos posts ficam
public_folder: "/images"

# Configuração para rodar localmente (opcional para testes)
local_backend: true

collections:
  - name: "posts"
    label: "Artigos"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Rascunho", name: "draft", widget: "boolean", default: true}
      - {label: "Imagem de Capa", name: "image", widget: "image", required: false}
      - {label: "Resumo", name: "summary", widget: "text", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Corpo do Texto", name: "body", widget: "markdown"}